version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: weekly
      day: "friday"
      time: "08:00"
      timezone: "Europe/Paris"
    target-branch: master
    assignees:
      - mbaumanndev
      - Mindstan
    labels:
      - dependencies
    rebase-strategy: disabled

  # Maintain dependencies for the Dockerfile
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: "friday"
      time: "08:00"
      timezone: "Europe/Paris"
    target-branch: master
    assignees:
      - mbaumanndev
      - Mindstan
    labels:
      - dependencies
    rebase-strategy: disabled